"""
JWT Signing utilities for consent tokens and video signatures.
"""
import os
import hashlib
from datetime import datetime, timedelta
from jose import jwt

JWT_SECRET = os.getenv("JWT_SECRET", "pratinidhi-ai-fallback-secret-key-12345")
ALGORITHM = "HS256"

def generate_consent_token(leader_id: str) -> str:
    """
    Generate a JWT token that proves the leader has given consent.
    Valid for 24 hours.
    """
    expire = datetime.utcnow() + timedelta(hours=24)
    to_encode = {
        "sub": leader_id,
        "type": "consent",
        "exp": expire
    }
    encoded_jwt = jwt.encode(to_encode, JWT_SECRET, algorithm=ALGORITHM)
    return encoded_jwt

def sign_video(video_path: str, leader_id: str, consent_token: str) -> dict:
    """
    Creates a SHA-256 hash of the generated video and signs it with a JWT
    to prove it was officially generated by the platform with consent.
    """
    # 1. Calculate SHA-256 of the video file
    sha256_hash = hashlib.sha256()
    
    # Check if file exists, if not just hash the path (for testing/mocking)
    if os.path.exists(video_path):
        with open(video_path, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        video_hash = sha256_hash.hexdigest()
    else:
        video_hash = hashlib.sha256(video_path.encode()).hexdigest()
        
    # 2. Create signature payload
    signature_payload = {
        "leader_id": leader_id,
        "video_hash": video_hash,
        "consent_token": consent_token,
        "timestamp": datetime.utcnow().isoformat(),
        "type": "video_signature"
    }
    
    # 3. Sign it
    signed_token = jwt.encode(signature_payload, JWT_SECRET, algorithm=ALGORITHM)
    
    return {
        "video_hash": video_hash,
        "signed_token": signed_token
    }
